name: Go check and build
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: Verify dependencies
        run: go mod verify
      - name: Check format
        run: test -z "$(gofmt -l $(find -type f -name '*.go'))"
      - name: Build
        run: go build -v ./...
